locals {
  env = try(yamldecode(file("${var.environment_configs_dir}/${var.ENV}-environment.yaml")), {})
}

resource "local_file" "vars_tf" {
  count           = length(var.variables) == 0 ? 0 : 1
  filename        = "${path.root}/env.tf.json"
  file_permission = "0444"
  content = jsonencode({
    variable = {
      for key, var in var.variables : key => {
        description = "Autogenerated environment variable"
        type        = var
      }
      role_arn = {
        type = "string"
      }
    }
  })
}

resource "local_file" "environment_tfvars" {
  count           = length(var.variables) == 0 ? 0 : 1
  filename        = "${path.root}/env.auto.tfvars"
  file_permission = "0444"
  content = provider::terraform::encode_tfvars(merge({
    for key, var in var.variables : key => local.env[key]
  },{role_arn = var.role_arn}))
}
